### PR TITLE
Added the GitHub .gitignore template.

### PR DESCRIPTION
**Pull request by HacDan**
Added the GitHub .gitignore template for GoLang projects.

---
This change is [Reviewable](https://reviewable.io/reviews/astroorbis/hashy/5)

### CODE REVIEW

**Comment by HacDan** [comment]
:lgtm:

**Review by AstroOrbis — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/astroorbis/hashy/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @HacDan)

**Comment by AstroOrbis** [comment]
Thank you!

**Comment by AstroOrbis** [comment]
Thank you!

**Pull request merged**
